.nh
.TH "SG" "1" "Nov 2023" "" ""

.SH NAME
.PP
sg-cleanup - Use this to reset what setup did.


.SH SYNOPSIS
.PP
\fBsg cleanup [flags]\fP


.SH DESCRIPTION
.PP
Use this to reset what setup did..

.PP
Here's a list of what that is:

.RS
.IP \(bu 2
Remove token from git config (use: git town)
.IP \(bu 2
Remove main branch config (use: git town)

.RE


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for cleanup


.SH SEE ALSO
.PP
\fBsg(1)\fP
