.nh
.TH "SG" "1" "Nov 2023" "" ""

.SH NAME
.PP
sg-setup - Setup everything to start the guide.


.SH SYNOPSIS
.PP
\fBsg setup [flags]\fP


.SH DESCRIPTION
.PP
Setup everything to start the guide..

.PP
This includes:

.RS
.IP \(bu 2
Github access token (use: git town)
.IP \(bu 2
What the main branch is (use: git town)

.RE


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for setup


.SH SEE ALSO
.PP
\fBsg(1)\fP
