.nh
.TH "SG" "1" "Nov 2023" "" ""

.SH NAME
.PP
sg-start - Command to start guide


.SH SYNOPSIS
.PP
\fBsg start [flags]\fP


.SH DESCRIPTION
.PP
Command to start guide.

.PP
You'll be guided through a story and learn how to apply the stacking workflow.

.PP
The story will teach you:
- Start feature
- Build on on-going features
- Sync all feature branches
- Ship feature branches


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for start


.SH SEE ALSO
.PP
\fBsg(1)\fP
