# .github/workflows/release.yml
name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write

jobs:
  lint:
    uses: ./.github/workflows/golangci-lint.yaml
  tests:
    needs: [lint]
    uses: ./.github/workflows/tests.yml
  goreleaser:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - 
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
